// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeguroVeiculos.Infrastructure.Data;

#nullable disable

namespace SeguroVeiculos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330133036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeguroVeiculos.Domain.Entities.Segurado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Segurados");
                });

            modelBuilder.Entity("SeguroVeiculos.Domain.Entities.Seguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeguradoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("SeguroVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SeguroVeiculos.Domain.Entities.Seguro", b =>
                {
                    b.HasOne("SeguroVeiculos.Domain.Entities.Segurado", "Segurado")
                        .WithMany()
                        .HasForeignKey("SeguradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeguroVeiculos.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SeguroVeiculos.Domain.ValueObjects.CalculoSeguro", "Calculo", b1 =>
                        {
                            b1.Property<Guid>("SeguroId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("PremioComercial")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Calculo_PremioComercial");

                            b1.Property<decimal>("PremioPuro")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Calculo_PremioPuro");

                            b1.Property<decimal>("PremioRisco")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Calculo_PremioRisco");

                            b1.Property<decimal>("TaxaRisco")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Calculo_TaxaRisco");

                            b1.Property<decimal>("ValorVeiculo")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Calculo_ValorVeiculo");

                            b1.HasKey("SeguroId");

                            b1.ToTable("Seguros");

                            b1.WithOwner()
                                .HasForeignKey("SeguroId");
                        });

                    b.Navigation("Calculo")
                        .IsRequired();

                    b.Navigation("Segurado");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
